name: Deploy web to Vercel
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Generate package-lock.json
        run: |
          cd web
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only
          fi
      - name: Install dependencies
        run: |
          cd web
          npm install --legacy-peer-deps
      - name: Build
        run: |
          cd web
          npm run build
      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd=web
