# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches: ['master', 'master_br_prot']
  pull_request:
    branches: ['master']
  schedule:
    - cron: '16 4 * * 1'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      #actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: List files before ESLint
        run: ls -la /home/runner/work/bidstreet/bidstreet

      - name: Run ESLint
        run: |
          npx eslint . --config .eslintrc.js --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file /home/runner/work/bidstreet/bidstreet/eslint-results.sarif
        continue-on-error: true
        id: eslint

      - name: List files after ESLint
        run: ls -la /home/runner/work/bidstreet/bidstreet

      - name: Check if SARIF file exists
        run: test -f /home/runner/work/bidstreet/bidstreet/eslint-results.sarif && echo "SARIF file exists" || echo "SARIF file does not exist"

      - name: Print ESLint output
        run: echo "${{ steps.eslint.outputs.stdout }}"

      - name: Check ESLint errors
        run: echo "${{ steps.eslint.outputs.stderr }}"

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /home/runner/work/bidstreet/bidstreet/eslint-results.sarif
          wait-for-processing: true
